"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

global___ColumnType = ColumnType
class _ColumnType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ColumnType.V], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
    INT64 = ColumnType.V(1)
    STRING = ColumnType.V(2)
    FLOAT64 = ColumnType.V(3)
class ColumnType(metaclass=_ColumnType):
    V = typing.NewType('V', builtins.int)
INT64 = ColumnType.V(1)
STRING = ColumnType.V(2)
FLOAT64 = ColumnType.V(3)
