syntax = "proto3";
package secret_store_api;

// An entry in the secret store
message SecretStoreEntry {
   bytes content = 1;
   bytes state = 2;
}

/// Add a new secret to the store
message CreateSecretRequest {
   SecretStoreEntry secret = 1;
}

message CreateSecretResponse {
    string id = 1;
}

/// Get a single secret from the secret store
message GetSecretRequest {
    string id = 1;
    uint32 version = 2;
}

message GetSecretResponse {
   SecretStoreEntry secret = 1;
   uint64 casIndex = 2;
}

/// Remove a particular secret
message RemoveSecretRequest {
    string id = 1;
    uint64 expectedCasIndex = 2;
}

message RemoveSecretResponse {
    /// Removal can fail because the expected cas index doesn't match
    bool removed = 1;
}

/// Remove a particular secret
message UpdateSecretAclRequest {
    string id = 1;
    bytes newAcl = 2;
    uint64 expectedCasIndex = 3;
}

message UpdateSecretAclResponse {
    /// Update can fail because the expected cas index doesn't match
    bool updated = 1;
}

message SecretStoreRequest {
    oneof request {
        CreateSecretRequest createSecret = 1;
        GetSecretRequest getSecret = 2;
        RemoveSecretRequest removeSecret = 3;
        UpdateSecretAclRequest updateSecretAcl = 4;
    }
}

message SecretStoreResponse {
    oneof response {
        CreateSecretResponse createSecret = 1;
        GetSecretResponse getSecret = 2;
        RemoveSecretResponse removeSecret = 3;
        UpdateSecretAclResponse updateSecretAcl = 4;
    }
}

