# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google_dv_360_sink.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='google_dv_360_sink.proto',
  package='google_dv_360_sink',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18google_dv_360_sink.proto\x12\x12google_dv_360_sink\"\x1a\n\nSingleFile\x12\x0c\n\x04name\x18\x01 \x01(\t\"\t\n\x07RawFile\"L\n\x07ZipFile\x12\x34\n\nsingleFile\x18\x01 \x01(\x0b\x32\x1e.google_dv_360_sink.SingleFileH\x00\x42\x0b\n\tselection\"\x8d\x01\n\tSinkInput\x12\x12\n\ndependency\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x03raw\x18\x03 \x01(\x0b\x32\x1b.google_dv_360_sink.RawFileH\x00\x12*\n\x03zip\x18\x04 \x01(\x0b\x32\x1b.google_dv_360_sink.ZipFileH\x00\x42\x06\n\x04\x66ile\"\xd1\x01\n\"GoogleDv360SinkWorkerConfiguration\x12,\n\x05input\x18\x01 \x01(\x0b\x32\x1d.google_dv_360_sink.SinkInput\x12\x1d\n\x15\x63redentialsDependency\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x64vertiserId\x18\x03 \x01(\t\x12\x13\n\x0b\x64isplayName\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x1e\n\x16membershipDurationDays\x18\x06 \x01(\tb\x06proto3'
)




_SINGLEFILE = _descriptor.Descriptor(
  name='SingleFile',
  full_name='google_dv_360_sink.SingleFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='google_dv_360_sink.SingleFile.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=74,
)


_RAWFILE = _descriptor.Descriptor(
  name='RawFile',
  full_name='google_dv_360_sink.RawFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=85,
)


_ZIPFILE = _descriptor.Descriptor(
  name='ZipFile',
  full_name='google_dv_360_sink.ZipFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='singleFile', full_name='google_dv_360_sink.ZipFile.singleFile', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='selection', full_name='google_dv_360_sink.ZipFile.selection',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=87,
  serialized_end=163,
)


_SINKINPUT = _descriptor.Descriptor(
  name='SinkInput',
  full_name='google_dv_360_sink.SinkInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dependency', full_name='google_dv_360_sink.SinkInput.dependency', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='google_dv_360_sink.SinkInput.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='raw', full_name='google_dv_360_sink.SinkInput.raw', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zip', full_name='google_dv_360_sink.SinkInput.zip', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='file', full_name='google_dv_360_sink.SinkInput.file',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=166,
  serialized_end=307,
)


_GOOGLEDV360SINKWORKERCONFIGURATION = _descriptor.Descriptor(
  name='GoogleDv360SinkWorkerConfiguration',
  full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.input', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credentialsDependency', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.credentialsDependency', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advertiserId', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.advertiserId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.displayName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='membershipDurationDays', full_name='google_dv_360_sink.GoogleDv360SinkWorkerConfiguration.membershipDurationDays', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=519,
)

_ZIPFILE.fields_by_name['singleFile'].message_type = _SINGLEFILE
_ZIPFILE.oneofs_by_name['selection'].fields.append(
  _ZIPFILE.fields_by_name['singleFile'])
_ZIPFILE.fields_by_name['singleFile'].containing_oneof = _ZIPFILE.oneofs_by_name['selection']
_SINKINPUT.fields_by_name['raw'].message_type = _RAWFILE
_SINKINPUT.fields_by_name['zip'].message_type = _ZIPFILE
_SINKINPUT.oneofs_by_name['file'].fields.append(
  _SINKINPUT.fields_by_name['raw'])
_SINKINPUT.fields_by_name['raw'].containing_oneof = _SINKINPUT.oneofs_by_name['file']
_SINKINPUT.oneofs_by_name['file'].fields.append(
  _SINKINPUT.fields_by_name['zip'])
_SINKINPUT.fields_by_name['zip'].containing_oneof = _SINKINPUT.oneofs_by_name['file']
_GOOGLEDV360SINKWORKERCONFIGURATION.fields_by_name['input'].message_type = _SINKINPUT
DESCRIPTOR.message_types_by_name['SingleFile'] = _SINGLEFILE
DESCRIPTOR.message_types_by_name['RawFile'] = _RAWFILE
DESCRIPTOR.message_types_by_name['ZipFile'] = _ZIPFILE
DESCRIPTOR.message_types_by_name['SinkInput'] = _SINKINPUT
DESCRIPTOR.message_types_by_name['GoogleDv360SinkWorkerConfiguration'] = _GOOGLEDV360SINKWORKERCONFIGURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SingleFile = _reflection.GeneratedProtocolMessageType('SingleFile', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEFILE,
  '__module__' : 'google_dv_360_sink_pb2'
  # @@protoc_insertion_point(class_scope:google_dv_360_sink.SingleFile)
  })
_sym_db.RegisterMessage(SingleFile)

RawFile = _reflection.GeneratedProtocolMessageType('RawFile', (_message.Message,), {
  'DESCRIPTOR' : _RAWFILE,
  '__module__' : 'google_dv_360_sink_pb2'
  # @@protoc_insertion_point(class_scope:google_dv_360_sink.RawFile)
  })
_sym_db.RegisterMessage(RawFile)

ZipFile = _reflection.GeneratedProtocolMessageType('ZipFile', (_message.Message,), {
  'DESCRIPTOR' : _ZIPFILE,
  '__module__' : 'google_dv_360_sink_pb2'
  # @@protoc_insertion_point(class_scope:google_dv_360_sink.ZipFile)
  })
_sym_db.RegisterMessage(ZipFile)

SinkInput = _reflection.GeneratedProtocolMessageType('SinkInput', (_message.Message,), {
  'DESCRIPTOR' : _SINKINPUT,
  '__module__' : 'google_dv_360_sink_pb2'
  # @@protoc_insertion_point(class_scope:google_dv_360_sink.SinkInput)
  })
_sym_db.RegisterMessage(SinkInput)

GoogleDv360SinkWorkerConfiguration = _reflection.GeneratedProtocolMessageType('GoogleDv360SinkWorkerConfiguration', (_message.Message,), {
  'DESCRIPTOR' : _GOOGLEDV360SINKWORKERCONFIGURATION,
  '__module__' : 'google_dv_360_sink_pb2'
  # @@protoc_insertion_point(class_scope:google_dv_360_sink.GoogleDv360SinkWorkerConfiguration)
  })
_sym_db.RegisterMessage(GoogleDv360SinkWorkerConfiguration)


# @@protoc_insertion_point(module_scope)
